### ISSUE TITLE
IFC Improvements for better tree representation

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#131]
in Tekla BIMsight, IFCSpace information is represented by bounding box like meshes (not bounding boxes exactly, as it can be a hollow cuboid or weird shape). Assimp can also preserve this information by setting this on the assimp importer:

````
importer.SetPropertyBool(AI_CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS, false);
````

We need to make this as default setting, with an option to disable.

Spaces resides at the same level as geometry, so we need to make sure that they can be identified easily by appending (IFC Space) onto the name. i.e. `RDSGF01` becomes `RDSGF01 (IFCSpace)`

**Task List:**

- [x] by default, set AI_CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS to false
- [x] add option to disable space representation if wanted
- [x] Append IFC Space entries with "IFCSpace". I.e. RDSGF01` becomes `RDSGF01 (IFCSpace)`
- [x] Make IFC Space entries appear first in selection tree
- [x] Set visibility toggle to false on IFC Space objects by default (Field in json tree. `item.toggleState==='visible'` is what is used on the front end to determine visibility)

**Comment by carmenfan** [comment]
All done. merging into v1.3.1

The invisibility feature doesn't work on Repo IO at the moment, it requires the web frontend to register the field. https://github.com/3drepo/3drepo.io/issues/235
