### ISSUE TITLE
Alluxio S3 Proxy requires additional aws sdk settings

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepobouncer#364]
### Description

as per 

https://github.com/3drepo/3drepo.io/issues/1885

In order to test using the Alluxio S3 proxy, we need to be able to configure a few extra settings on the AWS SDK.

We need to be able to reconfigure the endpoint to localhost:39999 and the path to the s3 api. 

The details are referenced in this document.
https://docs.alluxio.io/os/user/stable/en/api/S3-API.html

### Goals

- [ ] Able to configure the settings as required

### Tasks

- [ ] Enable AWS SDK in package.json
- [ ] Configuration options able to describe changing the endpoint
- [ ] Configuration options able to describe changing path
- [ ] Configuration options able to describe changing the security (ie. no https)

**Comment by carmenfan** [comment]
this isn't gonna be a package.json change, we use the c++ AWS client on the bouncer (since it's the bouncer code that actually does the writes)

So we need to figure out how to do this on the C++ Client - by the sound of that page they have their own S3 clients?

**Comment by keifgwinn** [comment]
They’ve got a Java and a go native client 

It looks like they’ve abandoned their c++ port pushing people to use the posix api. 

 https://alluxio.atlassian.net/browse/ALLUXIO-51

It would probably be the s3 rest proxy for what i imagine would be the least work. 

--
Keif
