### ISSUE TITLE
Option for detailed stats monitoring of processed files

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepobouncer#400]
### Description
We would like to have some more statistical information about when models are processed, and what they used.

total number of models processed
Type of model file 
File extension vs 
size vs 
Processing time
Storage requirement
Upload failures vs file type
Upload failures vs error code
Upload failures vs Account

### Goals
- [x] Design elastic record schema
- [x] Make configuration optional to emit to elastic

### Tasks

- [x] Establish processing monitoring capabilities
- [x] Gather all the information required into an elastic packet
