### ISSUE TITLE
Upgrade to ODA 2021

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#424]
### Description
Make necessary changes to utilise ODA 2021 instead.

### Goals
- [x] Make ODA 2021 compile with 3drepobouncer
- [x] Run RVT test to ensure things that passes doesn't fail
- [x] Check that revit 2021 files work

### Tasks

- [x] Make necessary code/cmake changes to compile 3drepobouncer with ODA 2021
- [x] update travis with latest libs
- [x] add revit 2021 file to test
- [x] Run revit test script
