### ISSUE TITLE
unhandled promise rejection in message decoder

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#428]
### Description
Messages can get stuck in the queue if for some reason bouncer_worker cannot find the instruction json.

![image](https://user-images.githubusercontent.com/11945337/106459584-f80f9500-6489-11eb-9164-b874f3d33071.png)

We need to catch it and return error message

### Goals
- [x] Should fail at init if shared_dir doesn't eixst
- [x] if *.json doesn't exist, it should catch the error gracefully and return an error message back on callbackq
- [x] on exitAfter mode, the process should wait for the predefined time limit for a new task before exiting

### Tasks
- [x] At init, check if shared_dir exists as part of the health test
- [x] catch promise rejection from message decoder, send apprioriate error message back to callbackq

Also extra requests:
- [x] On exit after N task mode, introduce a timer to wait for tasks before exiting.
