### ISSUE TITLE
IFC Parameter Support

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#447]
### Description

Current IFC implementation does not copy all the IFC information to the meta data object. We are also only including location data in the IFC tree, which means we can't perform Smart Group validation against it

### Goals

- [x] [Get all "element specific" data and place it in the metadata object](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800451844)
- [x] [Include the object name in the metadata object](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800459686)
- [x] [Include other identifiable information in the metadata object](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800482520)
- [x] [Include Location Data in the metadata object](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800484632) (NOTE: only extracting project/building/storey)
- <del> [Include Geometry Data in the metadata object](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800484632) </del> - out of scope as it's calculated at run time in BIMVision
- [x] [Include 2D Data from IFC](https://github.com/3drepo/3drepobouncer/issues/447#issuecomment-800486701)
- [x] Find units for metadata
- [x] Unicode support on units

### Related Resources

**School Model**
[Link to example model on 3D Repo - use support account](https://www.3drepo.io/viewer/mid_group/54f1cf20-8250-11eb-90e4-594342e39ba0)
[Link to example model IFC on Dropbox](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/Clients/Prospects/Mid%20Group/3D%20Models/P1035-BBA-Z0-ZZ-MR-A-0001-Building_Model_Ver9.ifc)

**Clinic Model**
[Link to example model on 3D Repo ](https://www.3drepo.io/viewer/mosment3d/c83ae060-fdae-11ea-941f-8d68670ee576/A)
[Link to example model IFC on Dropbox](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/3D%20Models/Clinic%20RVT%20-%20New%20Demo%20Models/IFC?preview=Clinic_S.ifc)

**Comment by mosment3DRepo** [comment]
### Get all "element specific" data and place it in the metadata object

The example model (link above) when opened in BIMVision includes additional properties under the "Element Specific" heading which are not present in 3D Repo

![image](https://user-images.githubusercontent.com/62879582/111351285-ef120600-867a-11eb-997c-9949cad1ba30.png)

![image](https://user-images.githubusercontent.com/62879582/111351354-0224d600-867b-11eb-9775-3a053975f0bc.png)

**Comment by mosment3DRepo** [comment]
### Include the object name in the metadata object

Currently 3D Repo uses the element name in the tree, in other tools this is available when reviewing meta data too. We should take the element name and include it in the metadata for the element so it can be queries using groups and accessed via the API

![image](https://user-images.githubusercontent.com/62879582/111352860-92174f80-867c-11eb-98e3-1dde7429e610.png)

**Comment by mosment3DRepo** [comment]
### Include other quantity information in the metadata object

Opening the **School** example model in BIMVision you can see additional sets of data outside of the standard "Element Specific" data. Including "AC_Equantity_Cube_22" and "AutoCADQuantities"

The headings of these parameters varies so any solution should adapt to multiple sets of data

![image](https://user-images.githubusercontent.com/62879582/111354329-1cac7e80-867e-11eb-876f-d340405a770e.png)

**Comment by mosment3DRepo** [comment]
### Include Location Data in the metadata object

Currently we are only including location data in the model tree, we should also bring this data into the meta data object

![image](https://user-images.githubusercontent.com/62879582/111357367-271c4780-8681-11eb-9cc5-e8c45876b4fa.png)

**Comment by mosment3DRepo** [comment]
### Include Location Data in the metadata object

Currently we are not processing the Geometry data in a way the user can read, we should also bring this data into the meta data object

![image](https://user-images.githubusercontent.com/62879582/111357367-271c4780-8681-11eb-9cc5-e8c45876b4fa.png)

**Comment by mosment3DRepo** [comment]
### Include 2D Data from IFC

The **School** example includes 2D information relating to gridlines and door swing profiles. Now we support 2D lines we should include this support for IFC models

![image](https://user-images.githubusercontent.com/62879582/111357768-81b5a380-8681-11eb-95ce-eb1c0da47a42.png)

**Comment by carmenfan** [comment]
> ### Include Location Data in the metadata object
> Currently we are only including location data in the model tree, we should also bring this data into the meta data object
> 
> ![image](https://user-images.githubusercontent.com/62879582/111357367-271c4780-8681-11eb-9cc5-e8c45876b4fa.png)

@mosment3DRepo 

Some more info on elevation:

short answer: No easy way to retrieve it

Quick google on IFCOpenShell forum, the devs are pretty much asking people to deduce it from bounding box (i.e. no quick function to call to get it): https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/d17fdfda/?limit=25

Looking at the standards there's explanation on how to retrieve these for particular objects, e.g. for [IFCSpace](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcproductextension/lexical/ifcspace.htm):
![image](https://user-images.githubusercontent.com/11945337/114723225-6ac2a980-9d32-11eb-9602-5e630b192bb8.png)

But not all IFCType has this. (e.g. I can see BIMVision has elevation values for each window) - so I think this has to be calculated.

So treating this part the same of geometry data -> out of scope 😆
