### ISSUE TITLE
Do not assume axis orientation with FBX imports

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#456]
## Description
We currently assume FBX files comes in on user space coordinates (i.e Z up) Whilst this is mostly the case but  it's not always.
Assimp doesn't auto transform the coordinates for us. but by the sound of [this](https://github.com/assimp/assimp/issues/849#issuecomment-539920386) we can find out and adjust accordingly
NOTE: if we do this we need to make sure we undo it if assimp ever decide to do this automatically!

## Tasks
- [x] Update build process to use the latest assimp (locally)
- [x] Establish current behaviour on import in the context of the coordinate systems involved
- [x] Find the API from assimp that can identify the up/forward axis (used blender export options to help)
- [x] Create the loop that imports fbx -> exports fbx/obj to test any flipping (assuming no flipping occurs on export)?
- [x] If the above step is too much of a pain in the ass then, just test in local 3drepo.io with the custom bouncer version)
- [x] Update the code to take the assimp detected up/forward axis
- [x] Test to confirm that import occurs as expected

## Related tickets
- https://github.com/3drepo/3drepobouncer/issues/405
- https://github.com/3drepo/3drepobouncer/issues/403

**Comment by har00n-haider** [comment]
@carmenfan for the ticket #405, what did you have in mind? I thought it might be good to tackle that as part of this ticket.

**Comment by carmenfan** [comment]
@har00n-haider  i think #405 is obsolete with this if you add tests.

basiclaly add tests on the importer and check if the boolean gives you the expected value is good enough i think.

**Comment by carmenfan** [comment]
@har00n-haider 

> Find the API from assimp that can identify the up/forward axis (used blender export options to help)

It should just be this https://github.com/assimp/assimp/issues/849#issuecomment-539920386

Aiscene is what we get when the file is imported. so we should have an instance of aiscene already: 
![image](https://user-images.githubusercontent.com/11945337/128345473-d4fd5ae3-d1ad-4cdb-b5d2-128f399388bf.png)

**Comment by har00n-haider** [comment]
@carmenfan  this might DOA. I am running through this loop and getting only the UnitScaleFactor entry. Just running it with the random FBX files on my PC.

![image](https://user-images.githubusercontent.com/72197495/128383045-5a80b5d0-ecf3-445a-a89a-1b5b056e7da6.png)


Result :

![image](https://user-images.githubusercontent.com/72197495/128383888-08ad88a5-d1b3-4bcb-9ef2-da2ec3bae8ab.png)
