### ISSUE TITLE
Support for Textures in Unreal

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#464]
### Description
Add texture information when exporting SRCs allowing textured models to be shown in Unreal.

### Goals
- [x] The SRC or its accompanying multipart Json should include enough information to load and show a texture for textured models

### Tasks
- [x] Find texture information for materials when building the map in SRCModelExport
- [x] Add the texture parameters to the mapping Json
- [x] Ensure that these details are the same as would be used to query the texture using the new [web API](https://github.com/3drepo/3drepo.io/issues/2571)

### Related Resources
Minimal examples of textured models for development: https://www.dropbox.com/sh/m3206ivyefukuz9/AADXiuDz8D3gOGyGzBwKduH6a?dl=0
