### ISSUE TITLE
Improvement deployment 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#473]
### Description
- reduce the size of deployment folder - only cherry pick things we need after compilation
- add some validity checks that can be optionally added in at compile time.

### Task
- [x] Add validity check
- [x] Add release packaging script
- [x] Ensure it pulls everything as needed
- [x] Add to travis to test the packaging script
