### ISSUE TITLE
DWG/DXF support

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#475]
### Description
Add support to dwg/dxf via Teigha library

### Goals
- [ ] DWG model file should be accepted and correct geometry generated
- [ ] DXF model file should be accepted and correct geometry generated

### Tasks
- [x] Add code to read dwg/dxf, use DGN Exporter to convert to dgn db.
- [x] Clean up code
- [x] Resolve crashing on clean up
- [ ] add test examples
