### ISSUE TITLE
IFC Open shell upgrade

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#478]
### Description
This issue aims to upgrade IFCOpenShell from v0.4 to v0.6. And look into how to support IFC4.

### Goals
- [ ] IFC 2x3 should upload as per before
- [ ] IFC 2x3 metadata should be retained
- [ ] IFC 4 supported

### Tasks
- [ ] Upgrade and compile IFCOpenShell
- [ ] Compile new IFCOpen shell into 3drepobouncer
- [ ] Test geometry still intact
- [ ] Test metadata still intact
- [ ] Test tree still intact
- [ ] Figure out how to support IFC 4 (expand this task when we've figured it out)
