### ISSUE TITLE
Move bouncer wrapper compilation to 3drepobouncer

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#485]
### Description
At the moment the bouncerwrapper is a separate compilation inside 3drepounity repository. This purely serves as an interop layer between C++ to external applications that are not written in C++.

It is historically placed there because assetBundleCreator is the only thing that uses it. However, the dependency is purely on the 3drepobouncer side, as it does not require any code from the unity repository.  This occasionally causes problems where 3drepobouncer and 3drepounity may go out of sync, and the developer has not recompiled 3drepounity, thus the unity processing crashes as the 3drepobouncer dll no longer has the same interface that 3drepobouncerWrapper was built with.

also with the addition of AssetBundleCreatorHelper, the process of setting up the assetBundleCreator now takes so many steps and is becoming more cumbersome. 

It would be good if we move the bouncer wrapper source code to be part of 3drepobouncer, and is part of the build process (as one of the options), so we can be certain that everytime you compile 3drepobouncer, bouncer wrapper is also updated and the bindings are always correct.

linked to https://github.com/3drepo/3drepounity/issues/395

### Goals
- Move bouncerwrapper sourcecode
- add additional flag in 3drepobouncer compilation to determine whether bouncer wrapper should be compiled.
- if flagged, bouncerwrapper should be compiled and placed in th dll folder (similar process as before)

### Tasks
- [x] place the wrapper code base under ./wrapper (everything under 3drepounity\BouncerWrapper)
- [x] update the bouncer Cmakelists to add a target for the wrapper 
- [x] update the wrapper Cmakelists  to remove elements no longer required (i.e. library detection etc.)
- [x] add a flag in the bouncer Cmakelists to optiononally add a project for the wrapper dll
- [x] place the output in the BOUCNCER_INSTALL\lib directory
- [x] update the bouncerwrapper function to pull the version directly from the dll
- [x] ammend the cmake call in the travis yaml to build the bouncerwrapper dll
- [x] add a line in the travis to run a some test on the wrapper function to confirm the critical functions used by the unity ABC work as expected
- [x] confirm that travis can succesfully build and test the bouncerwrapper dll
- [x] make the wrapper tests [dependant](https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html) on whether the wrapper was built
- [x] delete readme / shift to wiki

**Comment by har00n-haider** [comment]
@carmenfan 
This might be a dumb question. But do we even need the bouncer wrapper anymore? The client is directly accessing what in needs via the bounce dll ass:

- bouncerclient.exe > bouncer.dll
- someotherapp.exe > bouncerwrapper.dll > bouncer.dll

The bouncerwrapper is adding some new API, seemingly customized for easy use with Pinvoke style marshalling so it can be consumed more readily by C# code (no complex classes, everything is floats/ints/strings etc.). Shouldn't that be added directly in the main bouncer.dll itself, rather than go through the middle man? 

Or do we want to keep a distinction between two (core repo API for unmanaged usage vs  API customized for managed C# usage)

**Comment by carmenfan** [comment]
@har00n-haider I'd prefer to keep it separate. The bouncerwrapper have states and keeps pointers on behalf of the caller (the CSharp wrapper holds things like token/controller on behalf of the host application).

It doesn't make a lot of sense to be part of standard api offering

Plus it doesn't really have a significant impact at run time, and it gives the option to turn it off if the user isn't trying to build bouncer for unity.
