### ISSUE TITLE
Speed up model import

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#497]
### Description
We are getting some very detailed SPM files where there are lot of parent/children relationship, resulting in probing the mongo bson buffer to become a bottle neck.

This issue will try to hammer in enough optimisations for files mentioned in #496 to be able to be processed in under 3 hours.

### Goals
- [ ] Get model in #496 to be processed within the time limit

### Tasks
- [ ] Rewrite RepoBSON to stop relying on mongoBSON (or cache? which ever is more practical.)
- [ ] add multi threading where possible?
- [x] stop pulling unoptimised scene graph for unity process - we only use it to get a shared Id.

**Comment by carmenfan** [comment]
this is addressed in #574
