### ISSUE TITLE
Support for ODA BimNv Navisworks Import

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#518]
### Description
Adding the ODA BimNv library and importer class to support import of Navisworks NWD files.

### Goals
- [x] Bouncer `import` command recognises NWD files
- [x] 3D geometry is imported
- [x] 2D geometry is imported
- [x] Geometry is transformed/aligned correctly
- [x] All metadata extracted by the Navisworks plugin is created in the same form as the plugin
- [x] The hierarchy in the viewer matches that in Navisworks
- [ ] Grid system is imported as lines

### Tasks
- [x] Integrate BimNv binaries (update cmake, etc) and make sure BimNv works with existing ODA kernel (can link)
- [x] Create an importer class modelled on Revit, DWG, etc
- [x] Integrate class into bouncer file import command logic
- [x] Have the class iterate over the file and create some 3D geometry (either a flat list, or the first encountered etc) 
- [x] Add support for transforms
- [x] Add support for 2D lines
- [x] Make sure all materials are converted correctly
- [x] Refactor to match Navisworks hierarchy
- [x] Add metadata support
- [x] Test if metadata matches that of the Plugin
- [ ] Add support for grid system
- [x] Create tests

### Remarks
BimNv is installed by copying the contents of `BimNv_vc14_amd64dll_22.11.zip` into the `teigha_2022.11` directory, where `teigha_2022.11` is given as the `ODA_ROOT` environment variable.

### Questions
1. Do we support NWCs?
2. Do we want to open NWFs and report an error or let it be caught by `OdaModelImport`
(relevant files are file_processor.cpp line 54 & repo_model_import_oda.cpp line 13)

**Comment by sebjf** [comment]
Hi @mosment3DRepo, in Navisworks, the Arch Link Model has textures, but in the [reference import](https://staging.dev.3drepo.io/viewer/mosment3ddev/1d128090-478f-11ec-93c6-e3f089695f8b) it doesn't. Should the NWD import support textures?

**Comment by mosment3DRepo** [comment]
My reference at the moment would be to ignore textures for now, working on the basis that they could create very heavy models and they aren't that useful.

Since Navisworks models are likely to be several smaller models federated we should aim to keep them as light as possible.

**Comment by sebjf** [comment]
(Going to put the discussion about differences in here so we have a record!)

**Instanced Geometry**

![image](https://user-images.githubusercontent.com/5058369/150127582-b867f838-afcf-45f2-af95-5631552e9535.png)

The Plugin collapses `Geometry` into the `Instanced Geometry` node above it (the circled node on the far left) and does not show the `Instanced Geometry` node in the tree (basically, the Geometry Node adopts the Instanced Nodes metadata, but the node itself is deleted.

In Navisworks both are shown in the Standard View.

Which behaviour do we want for BimNv? (@mosment3DRepo)

**Comment by mosment3DRepo** [comment]
> ## Plugin Differences
> (Going to put the discussion about differences in here so we have a record!)
> 
> ### Category Ids
> For certain Categories, the Plugin creates an Element Id entry with the Id of the Parent Node. The corresponding entry in Navisworks does not have an Element Id block. (I am guessing we just leave this, i.e. BimNv will not adopt the parent Id. Nb, some Elements from the Plugin do _not_ have Ids either.)
> 
> ![image](https://user-images.githubusercontent.com/5058369/150128344-e875b981-b915-4a9a-8705-07269b9f5cbe.png)
> 

If I understand correctly, ideally we would want the Element ID dragged from the parent into the metadata for the selectable element, that way it will be picked up by smart groups

**Comment by mosment3DRepo** [comment]
> ### Instanced Geometry
> ![image](https://user-images.githubusercontent.com/5058369/150127582-b867f838-afcf-45f2-af95-5631552e9535.png)
> 
> The Plugin appears to collapse `Geometry` into the `Instanced Geometry` node above it (the circled node on the far left) and does not show the `Instanced Geometry` node in the tree (basically, the Geometry Node adopts the Instanced Nodes metadata, but the node itself is deleted.
> 
> It appears to do the same for `Instanced Groups` as well; in this case the actual tree node name is that of the `Group`, but the metadata is that of the `Instanced Group` parent. The one tree entry is an amalgamation of both. The node itself has the name of the `Group` but the metadata is the `Instance`. The `Geometry` as before take on the properties of their direct parent in the Navisworks tree.
> 
> ![image](https://user-images.githubusercontent.com/5058369/150150593-325cfdb7-e220-46b6-9c7c-6ba815304662.png)
> 
> In Navisworks both are shown in the Standard View.
> 
> Which behaviour do we want for BimNv? (@mosment3DRepo)

We want to mimic what's happening with the plugin as it was deliberate if I remember correctly, to have the parent metadata included in the child

**Comment by sebjf** [comment]
> We want to mimic what's happening with the plugin as it was deliberate if I remember correctly, to have the parent metadata included in the child

OK, great! And what about the collapsing of Instance nodes? Was that intentional or a side-effect?

**Comment by carmenfan** [comment]
> > We want to mimic what's happening with the plugin as it was deliberate if I remember correctly, to have the parent metadata included in the child
> 
> OK, great! And what about the collapsing of Instance nodes? Was that intentional or a side-effect?

I think this was intentional so the metadata falls in the right place

**Comment by sebjf** [comment]
> I think this was intentional so the metadata falls in the right place

On closer inspection it looks like *all* Collection nodes adopt their Parents Metadata. I will update the importer to match this behaviour too.

**Comment by carmenfan** [comment]
@sebjf the plugin code is here if it helps: https://github.com/3drepo/3drepoPlugin/blob/master/navis/Plugin/Helper/ModelExporter.cs#L85

**Comment by sebjf** [comment]
Hi @carmenfan,

Could I get your thoughts on a bug with the tree?

In short, meshes that should be seen as one are appearing as separate items when the scene is built via BimNv vs the plugin...

![image](https://user-images.githubusercontent.com/5058369/150391050-bb7581e7-c4a3-413a-8bff-f96cb95d1a80.png)

When looking at the tree json, the only difference I can see is that the plugin version (left) does not specify the metadata property, while the BimNv one (right) does,

![image](https://user-images.githubusercontent.com/5058369/150392373-e4f233b6-b672-4408-886c-87afed324803.png)

I would guess this is the metadata block shown in the BIM view, and that it controls whether an entry is created in the tree? Is that right?

If so, do you know how its decided whether entries are given the metadata field or not? I am certainly not specifying it directly or creating a second level etc!

**Comment by sebjf** [comment]
> No, it's governed by whether meshes have names.

Thank you Carmen!

I think this is done now but for one thing:

The Transform properties in the plugin export the transform as an axis-angle, and decompose matrix transforms into their components.
i.e.:
![image](https://user-images.githubusercontent.com/5058369/150783524-62552831-7cd1-43ff-ba0e-ecaa5d05753e.png)

In BimNv, the transforms are given in their raw representation and not decomposed. Converting quaternions to angle-axis, and extracting rotations and scale from matrices is a solved problem but the algorithms are quite complex. Ideally we would bring in a library like Eigen to do it, though we could create a function just for this. It would be another thing to maintain though.

@mosment3DRepo, you said before that transforms were not so important. Do we just leave it or do the conversions?

**Comment by mosment3DRepo** [comment]
> > No, it's governed by whether meshes have names.
> 
> Thank you Carmen!
> 
> I think this is done now but for one thing:
> 
> The Transform properties in the plugin export the transform as an axis-angle, and decompose matrix transforms into their components.
> i.e.:
> ![image](https://user-images.githubusercontent.com/5058369/150783524-62552831-7cd1-43ff-ba0e-ecaa5d05753e.png)
> 
> In BimNv, the transforms are given in their raw representation and not decomposed. Converting quaternions to angle-axis, and extracting rotations and scale from matrices is a solved problem but the algorithms are quite complex. Ideally we would bring in a library like Eigen to do it, though we could create a function just for this. It would be another thing to maintain though.
> 
> @mosment3DRepo, you said before that transforms were not so important. Do we just leave it or do the conversions?

We can leave them out, they are only in the Plugin version because we went for a belt & braces approach.

**Comment by sebjf** [comment]
Thanks! And we are leaving the grids out for this version too?
