### ISSUE TITLE
Upgrade ODA to 22.11

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#523]
### Description
Upgrade ODA libraries to 22.11. This is because we need the latest version of BimNv to get the metadata from Navisworks files.

### Goals
- [ ] Bouncer compiles with the 22.11 ODA binaries
- [ ] All tests pass
- [ ] Import functionality is unchanged

### Tasks
- [ ] Get the 22.11 binaries for existing products
- [ ] Rebuild bouncer solution with new binaries
- [ ] Fix API changes

**Comment by sebjf** [comment]
Hi @carmenfan @mosment3DRepo, I have this working, but with a couple things to discuss,

1. The biggest change is to the units system. In 22.11 BimRv uses a dedicated object to define Units at runtime (as opposed to one of a number of enums) for all parameters. 
I have refactored to use this new approach, and all the property values come through.
Some custom ones are missing units however. For example, in Mia's house project the doors define some of parameters. These are "lengths" but they don't have units defined (at least not units we know of); rather it seems the _Family_ has its own units schema, which are probably meters, but it doesn't matter because not being inbuilt, we don't know what they should be...

![image](https://user-images.githubusercontent.com/5058369/144622061-9a10936c-552e-42d5-ba55-d4adf4e7e056.png)

```
[03-12-2021 02:39:06][ERROR]: Unrecognised units type: autodesk.spec.aec:length-1.0.0 autodesk.parameter.aec.revit.family:49198-1.0.0 for Dimensions::Trim Projection Ext on B-90cm
```

I wonder if this had something to do with that odd snippet we spoke of the other day Carmen? Where it was getting the default units for a measure type?

The best approach may be to try and re-create that as a fallback where we can't resolve the true units for each property.

2. The other thing I've noticed is that some of the line elements are missing.

Again in Mia's model, `Furniture Layout GF - Review 01.dwg` 

![image](https://user-images.githubusercontent.com/5058369/144623547-51f71beb-07b3-4d6a-98a0-61f5d67fe289.png)

Is not loaded in 22.11. I am wondering if this could be to do with the ways we process the views. it doesn't show in Revit 2022 either, nor can I find it in the project view, and there is no record of the element in the tree.

![image](https://user-images.githubusercontent.com/5058369/144623685-8bd968e0-6513-43fb-a035-756978f98dad.png)

Could you (@mosment3DRepo) say anything more about this? I am not sure how this dwg is intended to interact with Revit. (I presume its embedded in the Revit file at least, since I can upload the .rvt to staging and have it show up).

**Comment by carmenfan** [comment]
> I wonder if this had something to do with that odd snippet we spoke of the other day Carmen? Where it was getting the default units for a measure type? 

Looking at your screenshot, it looks like Revit also does not display the units? IF that's the case I'm tempted to say if we were showing units previously we were just guessing... so maybe we can just go without for those, @mosment3DRepo ?

> Could you (@mosment3DRepo) say anything more about this? I am not sure how this dwg is intended to interact with Revit. (I presume its embedded in the Revit file at least, since I can upload the .rvt to staging and have it show up).

If you open the model with OdBimApp (should be in the exe folder) and visualise the model, do you see that geometry?

**Comment by sebjf** [comment]
> IF that's the case I'm tempted to say if we were showing units previously we were just guessing

OK, I think I see how to do it but will wait for @mosment3DRepo before implementing it.

> If you open the model with OdBimApp (should be in the exe folder) and visualise the model, do you see that geometry?

If I open the model with OdBimApp and try to "change view to default 3d view" it crashes to desktop... 🙄😢

**Comment by sebjf** [comment]
Hi @carmenfan @mosment3DRepo,

I am looking at the parameter differences with the new version of ODA. I have six test models that I am comparing programmatically. The parameters almost all seem OK, with some queries below:

1. As above, anything without an explicit unit just has no units, as opposed to default units for the type. For example,
`Replaced Parameter Overall Legend::b1 (m) with Overall Legend::b1`
`Replaced Parameter Dimensions::Length (m) with Dimensions::Length`
Is this the behaviour we want?

2. Material names are now resolved instead of DB handles(?). For example,
`"Materials and Finishes::ChairFrameMaterial" was "720933" now "Röshults - Stainless Steel (Anthracite)"`
`"Material" was "490128" now "Metal - Paint Finish - Ivory, Matte"`
`"Frame" was "345954" now "Black Plastic"`
`"BOS_0_Material" was "702863" now "b77382e0_768c_483e_a02b_a204e6c49a30"`
I am guessing this is good?

3. What looks like stringified enums are now resolved to localised strings. For example,
`"Mechanical::System Classification" was "S_TWarmwasser" now "Domestic Hot Water"`
`"Mechanical::System Classification" was "Abwasser" now "Sanitary"`
Again is this OK? (i.e. there isn't an external dependency that assumes the metadata is db handles or enums?)

4. Some `"Mechanical::Section"` parameter values are different, for example:
`"Mechanical::Section" was "12" now "143"`
`"Mechanical::Section" was "32" now "38"`
`"Mechanical::Section" was "133" now "19"`
I am not sure of the implications of this one...

5. A number of electrical ratings have changed, for example:
`"Electrical - Circuiting::Electrical Data" was "230 V/1-4500 VA" now "230 V/1-1500 VA"`
`"Electrical - Circuiting::Electrical Data" was "230 V/3-13500 VA" now "400 V/3-13500 VA"`
I am going to guess that this is a built-in property that has changed underneath, but it looks to me quite significant. Perhaps we should report to ODA?

6. These two parameters are missing on all the models.
`Construction::Automatically Embed`
`Graphics::Display in Hidden Views`
I am guessing these are visualisation options that we don't care about?

7. This parameter is missing: `Loads::Feed Through Lugs Current Phase A (A)`. 
Looking at the objects that it showed up on, it seems its been deprecated in favour of `Loads::Feed Through Lugs Apparent Load Phase A"`

8. This parameter is missing: `Electrical - Circuiting::Electrical Data`.
Looking at the objects that it showed up on, it is indeed missing, but was previously always invalid/null? As all the entries had the value:
`Electrical - Circuiting::Electrical Data: 0 V/1-0 VA`

9. This parameter is missing: `Dimensions::Length (mm)`, but only/always on `Pipe Insulation`.

10. This parameter is missing: `Mechanical::Area (m²)` but only on one element (`Flex Pipe Round`) in one model (`Sample House_MEP With Section Box`), and it was set to 0 on that model before.

**Comment by sebjf** [comment]
The new build of Bouncer prints a number of errors of the following type when importing some models,

` FreeImage_LoadU: failed to open input file`

This occurs expectedly on models such as Mia's house which have local textures defined, but also on, e.g. `rac_advanced_sample_project.rvt`

Profiling the client during import shows that this seems to be due to its search process for the textures,

![image](https://user-images.githubusercontent.com/5058369/145815058-c5c97b52-dedb-4af5-bf30-d05584a85028.png)

Which it does eventually succeed at.

**Comment by sebjf** [comment]
Other noted differences are in the tessellation,

Before
![image](https://user-images.githubusercontent.com/5058369/145837549-87c3491e-2bf9-4778-b196-9227309a780a.png)
After
![image](https://user-images.githubusercontent.com/5058369/145837522-15324424-1870-47d3-9ac3-bcf38714264f.png)


The materials are also slightly different. It looks like the specular is higher on the newer models.

The window tints and siding colours are slightly different on the rac and chapel projects, for example,

Before
![image](https://user-images.githubusercontent.com/5058369/145838139-52baf25c-5f27-4bfa-846f-cd1ecb34423b.png)
After
![image](https://user-images.githubusercontent.com/5058369/145838082-65483417-4766-4052-b6ec-378e4dd6b34e.png)

Note that the new version of ODA (22) matches more closely what is seen when opening the file in Revit.

The new version of ODA does not import the outlines for some parts of the Sample House, though it still imports isolines. Is there an option in the Revit file itself to control this? The new version does export lines for Mia's house model and some parts of the Sample House with Custom Parameters (on a per-element basis) suggesting its a material option or similar.

Before
![image](https://user-images.githubusercontent.com/5058369/145838699-1e38bc05-75ca-4a60-a5a8-18265b548ae6.png)
After
![image](https://user-images.githubusercontent.com/5058369/145838628-067aca60-b2b9-447d-8c4c-b6aa60f7b40e.png)

The new version seems to handle UVs better too,

![image](https://user-images.githubusercontent.com/5058369/145839054-6c554954-c92c-4baf-90e2-84a90cded4a0.png)
vs
![image](https://user-images.githubusercontent.com/5058369/145839073-e6992dc8-5384-4a32-b7f4-1d0c3243fc90.png)

**Comment by mosment3DRepo** [comment]
> > I wonder if this had something to do with that odd snippet we spoke of the other day Carmen? Where it was getting the default units for a measure type?
> 
> Looking at your screenshot, it looks like Revit also does not display the units? IF that's the case I'm tempted to say if we were showing units previously we were just guessing... so maybe we can just go without for those, @mosment3DRepo ?
> 
> > Could you (@mosment3DRepo) say anything more about this? I am not sure how this dwg is intended to interact with Revit. (I presume its embedded in the Revit file at least, since I can upload the .rvt to staging and have it show up).
> 
> If you open the model with OdBimApp (should be in the exe folder) and visualise the model, do you see that geometry?

Yes, I would say in times of ambiguity we should err on the side of caution and not display anything. If we make an assumption and it is wrong then we get the blame.

**Comment by mosment3DRepo** [comment]
> Hi @carmenfan @mosment3DRepo,
> 
> I am looking at the parameter differences with the new version of ODA. I have six test models that I am comparing programmatically. The parameters almost all seem OK, with some queries below:
> 
> 1. As above, anything without an explicit unit just has no units, as opposed to default units for the type. For example,
>    `Replaced Parameter Overall Legend::b1 (m) with Overall Legend::b1`
>    `Replaced Parameter Dimensions::Length (m) with Dimensions::Length`
>    Is this the behaviour we want? **YES**
> 2. Material names are now resolved instead of DB handles(?). For example,
>    `"Materials and Finishes::ChairFrameMaterial" was "720933" now "Röshults - Stainless Steel (Anthracite)"`
>    `"Material" was "490128" now "Metal - Paint Finish - Ivory, Matte"`
>    `"Frame" was "345954" now "Black Plastic"`
>    `"BOS_0_Material" was "702863" now "b77382e0_768c_483e_a02b_a204e6c49a30"`
>    I am guessing this is good? **YES - much better**
> 3. What looks like stringified enums are now resolved to localised strings. For example,
>    `"Mechanical::System Classification" was "S_TWarmwasser" now "Domestic Hot Water"`
>    `"Mechanical::System Classification" was "Abwasser" now "Sanitary"`
>    Again is this OK? (i.e. there isn't an external dependency that assumes the metadata is db handles or enums?) **YES**
> 4. Some `"Mechanical::Section"` parameter values are different, for example:
>    `"Mechanical::Section" was "12" now "143"`
>    `"Mechanical::Section" was "32" now "38"`
>    `"Mechanical::Section" was "133" now "19"`
>    I am not sure of the implications of this one... 
> 5. A number of electrical ratings have changed, for example:
>    `"Electrical - Circuiting::Electrical Data" was "230 V/1-4500 VA" now "230 V/1-1500 VA"`
>    `"Electrical - Circuiting::Electrical Data" was "230 V/3-13500 VA" now "400 V/3-13500 VA"`
>    I am going to guess that this is a built-in property that has changed underneath, but it looks to me quite significant. Perhaps we should report to ODA?
> 6. These two parameters are missing on all the models.
>    `Construction::Automatically Embed`
>    `Graphics::Display in Hidden Views`
>    I am guessing these are visualisation options that we don't care about? **YES - since the plugins respond the the current view I would assume these are graphics related**
> 7. This parameter is missing: `Loads::Feed Through Lugs Current Phase A (A)`.
>    Looking at the objects that it showed up on, it seems its been deprecated in favour of `Loads::Feed Through Lugs Apparent Load Phase A"`
> 8. This parameter is missing: `Electrical - Circuiting::Electrical Data`.
>    Looking at the objects that it showed up on, it is indeed missing, but was previously always invalid/null? As all the entries had the value:
>    `Electrical - Circuiting::Electrical Data: 0 V/1-0 VA`
> 9. This parameter is missing: `Dimensions::Length (mm)`, but only/always on `Pipe Insulation`.
> 10. This parameter is missing: `Mechanical::Area (m²)` but only on one element (`Flex Pipe Round`) in one model (`Sample House_MEP With Section Box`), and it was set to 0 on that model before.

**Comment by sebjf** [comment]
> .. in Mia's model, Furniture Layout GF - Review 01.dwg .. is not loaded in 22

After discussing with Mia, it seems this is a Linked file. It can be seen in Revit by looking at `Revit Links` in the `Project Browser`, right click > `Manage Links...` > `CAD Formats`.

The `house with textures` model has two such DWGs that both show up in the old version of ODA, but not 22.
