### ISSUE TITLE
Connect to Mongo replica set

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#524]
### Description
At the moment, the configuration designed in such a way that we only take in one host and one port. We need to modify this so we can take in a replica set connection

### Config change
The config file that gets passed to bouncerClient will now accept `connectionString` , or the old `dbhost` and `dbport` (the latter takes precedence, so ensure they are removed if you are trying to use connection string.

Connection string should be as defined by mongo, for e.g. you can connect to an individual instance as like this:
![image](https://user-images.githubusercontent.com/11945337/144647571-c920e222-78ec-4a7b-820d-981f10ed39a6.png)

### Goals
- To be able to connect to a replica set

### Tasks
- [x] Add the ability to instantiate a db handler with a connection string
   - [x]  Ensure errors are caught correctly if the string is not a valid connString.
   - [x] Ensure both repl Set and single instances can connect successfully
- [x] Wire the function above all the way up to RepoController
- [x] Alter bouncer config and bouncerClient to parse and understand this change 
  - [x] Ensure the old config still works for minimal disruption
- [ ] Clean up
  - [ ] There's a BSONCredential way of connecting, which i believe is for the old RepoGUI - which we can remove
  - [ ] Tests
