### ISSUE TITLE
Adjust for daylight savings within Sequences

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#527]
### Description
This issue is related to https://github.com/3drepo/3drepobouncer/issues/526 and https://github.com/3drepo/3drepo.io/issues/2892

We need to adjust for daylight savings on any countries that has it. 

### Goals
- [ ] Consider areas where daylight savings created a different offset at different parts of the year in certain countries (https://en.wikipedia.org/wiki/Daylight_saving_time_by_country) which will need to be considered based on the year of the date in Synchro
- [ ] Ensure the above change is applied on:
  - [ ] Sequence frame dates
  - [ ] Activities dates
  - [ ] Metadata within activities.

### Tasks
To be filled in by the developer

**Comment by carmenfan** [comment]
not needed, as it will be done in #526
