### ISSUE TITLE
disable animation flag is broken 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#529]
### Description
This is a pairing issue for https://github.com/3drepo/3drepo.io/issues/2868

bouncer is also not reading in the configuration correctly.

### Steps to replicate
See https://github.com/3drepo/3drepo.io/issues/2868

### Current Behaviour
- the flag is being ignored, it's being imported regardless

### Expected Behaviour
- if importAnimations is disabled, it should not import the transformation and split up the super meshes

### Tasks
- [ ] Build bouncer with synchro libary on staging 
- [ ] build abc on staging
- [ ] run bouncer 3drepo.io context ( using the branch specified above)
- [ ] test with a given synchro file
