### ISSUE TITLE
Add support for Model Streaming

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#570]
### Description
Add support for processing models in a way that makes them amenable for effective streaming.

For streaming to behave sensibly as the camera moves, supermeshes (which are the unit that is streamed in and out) should consist of geometry that is spatially coherent, and be of a similar size (geometric complexity wise).

The modifications to bouncer will take place after the grouping stage (where supermeshes are grouped based on their Syncro transforms, texture usage, format etc). Each set will then undergo a process to turn them into a set of supermeshes. The submeshes will be organised into a BVH based on bounds. Then the tree will be traversed to find the highest level nodes that fall below the vertex limit. All the submeshes for these nodes will form a supermesh.

Where a leaf node with one supermesh greater than the vertex limit is encountered, this submesh will be split at the triangle-level in a spatially coherent way to output multiple supermeshes, each under the vertex limit.

Current behaviour is that the stash graph is created in MultipartOptimizer::generateMultipartScene.

The supermeshes are sorted by sortMeshes. This takes into account four dimensions over which meshes are grouped:

1. The actual group name
2. The format
3. The texture (if any) the mesh uses
4. The transparency setting

Within each combination multiple sets can be created, taking into account the rough geometric size of the mesh.

All the sets are then processed, with one set being turned into one supermesh, by processMeshGroup, which itself uses createSuperMesh. createSuperMesh uses the node UUIDs to build a new node by requesting the geometric data for each in turn and adding it into a set of arrays along with mappings showing where the data sits within the arrays (collectMeshData).

collectMeshData itself works by iterating over the scene and checking each entry against the list of UUIDs that it should group. It does this so that transformation nodes are applied to the geometry before they are collected.

The modification to build spatially coherent meshes should take place in processMeshGroup (per-group). To support hard vertex limits, we need to add a new function to split a UUID in a spatially coherent manner, in addition to combing them.

### Goals

- [ ] Bouncer builds supermeshes that contain spatially coherent submeshes
- [ ] Bouncer builds supermeshes that remain sensibly grouped (i.e. similar transforms together, textures on their own)
- [ ] Supermeshes always have less than 65k vertices
- [ ] Supermeshes aim to be around 65 k vertices

### Tasks

- [x] Add the geometry sizes to the database for 3065 to read
- [x] Add new type to allow multipart geometry to be handled atomically
- [x] Split collectMeshData so data so it appends a mesh_mapping_t with a single UUID
- [x] Add a new function to split a baked `MeshNode` into multiple of the `mapped mesh` containers with a simple algorithm.
- [x] Update `createSuperMesh` to use sets of the new mapped mesh types, outputting multiple `MeshNode`s.
- [x] Update `processMeshGroup` to support multiple meshes returned from `createSuperMesh`
- [x] Add BVH library to Bouncer
- [x] Create BVH nodes for UUIDs
- [x] Extend `processMeshGroup` to build a BVH for the group
- [x] Implement algorithm to collect UUID sets from BVH
- [x] Remove vertex/face count grouping logic from `sortMeshes`
- [x] Implement spatially coherent splitting algorithm for the `MeshNode`s.

### Related Resources

Viewer Issue: https://github.com/3drepo/3drepounity/issues/422
.io Issue: https://github.com/3drepo/3drepo.io/issues/3065

**Comment by sebjf** [comment]
Hi @carmenfan, I am modifying the unityAssets.json to contain supermesh metadata.

Right now, I have just modified `makeRepoUnityAssets` to build bson objects implicitly in the function, e.g.

```
RepoUnityAssets RepoBSONFactory::makeRepoUnityAssets(
	const repo::lib::RepoUUID                   &revisionID,
	const std::vector<std::string>              &assets,
	const std::string                           &database,
	const std::string                           &model,
	const std::vector<double>                   &offset,
	const std::vector<std::string>              &vrAssetFiles,
	const std::vector<std::string>              &iosAssetFiles,
	const std::vector<std::string>              &androidAssetFiles,
	const std::vector<std::string>              &jsonFiles,
	const std::vector<std::shared_ptr<repo::core::model::MeshNode>> &meshes)
{
	RepoBSONBuilder builder;

	builder.append(REPO_LABEL_ID, revisionID);

	if (assets.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_ASSETS, assets);

	if (!database.empty())
		builder.append(REPO_LABEL_DATABASE, database);

	if (!model.empty())
		builder.append(REPO_LABEL_MODEL, model);

	if (offset.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_OFFSET, offset);

	if (vrAssetFiles.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_VRASSETS, vrAssetFiles);

	if (iosAssetFiles.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_IOSASSETS, iosAssetFiles);

	if (androidAssetFiles.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_ANDROIDASSETS, androidAssetFiles);

	std::vector<RepoBSON> metadatas;

	for (auto mesh : meshes)
	{
		RepoBSONBuilder metabuilder;
		metabuilder.append("numFaces", mesh->getNumFaces());
		metabuilder.append("numVertices", mesh->getNumVertices());
		metadatas.push_back(metabuilder.obj());
	}

	if (metadatas.size())
		builder.appendArray(REPO_UNITY_ASSETS_LABEL_METADATA, metadatas);

	return RepoUnityAssets(builder.obj());
}
```

Producing, e.g. (ps. I know the json files list is missing!)

```
{
	"models": [
		{
			"_id": "ArB2QJSgEey9fWGQCQvBNw==",
			"assets": [
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/a276dd49-814b-4043-8864-fd3293ceecd2.unity3d",
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/ea412236-4a23-43de-817e-779a5666f919.unity3d",
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/88beab78-9654-4f40-9c45-aa5bab4f3ec2.unity3d",
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/d26ceae7-beb2-40ae-8985-bcad5b7bc416.unity3d",
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/c76fbdc9-3568-41b6-af1d-0d7f680b112d.unity3d",
				"/WebGLStreamingDemo/fb450c40-949f-11ec-bd7d-6190090bc137/36e902a8-11da-4868-9e0e-b74bdf2cd1b4.unity3d"
			],
			"database": "WebGLStreamingDemo",
			"model": "fb450c40-949f-11ec-bd7d-6190090bc137",
			"offset": [
				-243171.5327005652,
				-1000.0000000000694,
				153159.77280001719
			],
			"assetMetadata": [
				{
					"numFaces": 48746,
					"numVertices": 101001
				},
				{
					"numFaces": 7104,
					"numVertices": 9504
				},
				{
					"numFaces": 146,
					"numVertices": 50
				},
				{
					"numFaces": 62507,
					"numVertices": 98997
				},
				{
					"numFaces": 78,
					"numVertices": 152
				},
				{
					"numFaces": 65737,
					"numVertices": 100583
				}
			]
		}
	]
}
```

Would you prefer to continue like this and keep everything to do with unityAssets.json in that function, or should I create a new RepoBSON type, e.g. `MeshInfoNode` to represent the metadata explicitly that can be created and passed around (instead of pointers to MeshNode)?

**Comment by carmenfan** [comment]
@sebjf  It depends whether this is something that we will need to build on, or we will only ever need the num faces and vertices from this stash of info.

It's probably better to alter the `MeshNode` to automatically store `numFaces` and `numVertices`, which should naturally apply to supermeshes.

Then just let 3drepo.io do the query (and I think we should create a new endpoint for this as you'd want this information for unreal as well?)

2 reasons for thinking of doing this way:
1. It's a relatively small data that is useful to have anyway within the mesh data, something that @mosment3DRepo request every so often to expose. If we store it in the mesh data then we have the flexibility to create endpoints for both super mesh and meshes for this purpose.
2. I think you will want this data outside of unity (e.g. unreal streaming),l so even if we cache this information, we don't want it in unityAssets.json I think.

**Comment by sebjf** [comment]
@carmenfan Yes that looks good thank you!

**Comment by carmenfan** [comment]
> @carmenfan Yes that looks good thank you!
> 
> (Where `_id` is the bundleid/the id used in the uri of the asset bundle, right?)

yes, which should be a 1 to 1 mapping to supermesh ids in the database

**Comment by carmenfan** [comment]
@sebjf  committed in the io branch:

As usual federation complicates everything a bit, so models response looks like this:

![image](https://user-images.githubusercontent.com/11945337/162990001-7988a4e4-fe5b-4802-b329-76baa64f957f.png)

And federation response looks like this:
![image](https://user-images.githubusercontent.com/11945337/162990291-eb2330c5-7dc1-43bd-aa2f-052dbc76ed76.png)


numbers default to 0 if they are not found 
![image](https://user-images.githubusercontent.com/11945337/162990476-84d87be8-5215-4d90-af0c-dc84c52b30ff.png)



Let me know if you need anything changed

**Comment by sebjf** [comment]
@carmenfan Thank you! I have updated the viewer and tested everything out and it works well.

I [changed](https://github.com/3drepo/3drepo.io/pull/3066/commits/b0975a3929e9f51b6059e39d629f3d246bf7b788) the way the bounding box was delivered as Unity's json parser doesn't support nested arrays. Let me know if this is OK.

@mosment3DRepo [Here](https://issue-3065.dev.3drepo.io/viewer/WebGLStreamingDemo/c8a0f750-9638-11ec-9f99-ff196bbba7b8) is the latest version running. 

You need to use `UnityUtil.unityInstance.SendMessage("StreamingManager","SetThreshold",1000000)` as usual (with a threshold around 1000000 or 1000000).

First impressions are that its stable and responsive from the start, but slow. This is because the FPS and the TCP transport is hit by the large number of bundles (~2400), which would be much lower on even much larger real models. Also, the response time for a 50Kb bundle on my machine currently is 40-50 ms, which seems high (no explanation).

I've left stats on by default.

![image](https://user-images.githubusercontent.com/5058369/163138586-c8409bf5-ad7a-488b-a0a0-c68416adf80b.png)

The Loaded Bundles are how many separate meshes are loaded (i.e. draw calls for the model itself), and Bundle Loading Tasks are how many are currently waiting to be loaded. These include requests queued internally and those in-flight to .io. Swing the camera around and you should see this fluctuate a lot.

Due to the way the new endpoint is coded, this version should actually work with all existing models. It will even have a partially sensible value for the size since existing `MeshNodes` all have a `face_count`. It won't be an accurate memory measure, or do anything sensible, but it will load!

![image](https://user-images.githubusercontent.com/5058369/163139728-941cd302-2b43-47f3-81bd-61c9e2c058f5.png)

**Comment by sebjf** [comment]
### Performance

From some initial comparisons, the 507 does take a lot longer than Staging, but only for larger models. Though what larger means is not obvious since the increase is not directly proportional to the number of elements or file size.

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Name | Size (Kb) | Nodes | Meshes |   | Staging | 507
-- | -- | -- | -- | -- | -- | --
Clinic_S | 6092 | 2176 |   |   | 02:07 | 01:40
Clinic_A | 16584 | 7656 |   |   | 01:40 | 02:57
20151105_11011-HQ-A-Skanska Building.rvt | 54332 | 25731 | 12955 |   | 09:56 | 09:32
Facade.rvt | 98940 | 7361 | 4115 |   | 07:06 | 07:24
103A1-MD603.rvt | 180452 | 94262 | 47099 |   | 21:59 | 151:20


</body>
</html>

(We could get a better image by running more models, especially if we know the element counts of some to get a better distribution.)

By visual inspection though, its obvious that the Sorting Meshes stage of 507 takes a considerable amount of time for the MD603. This starts about 5-7 minutes in - at the halfway point of Staging's import. Capturing a sample trace during this stage, we can see a couple of methods that have an outsized impact on the hot path.
(We cannot profile the entire import, because the profile itself would be too large.)

![image](https://user-images.githubusercontent.com/5058369/190610873-1a3bea8b-beda-4b4d-b208-89b2abb112e5.png)

The getTransMatrix() method is used by the MultipartOptimiser to bake all nodes before spatial supermeshing. This baking stage doesn't occur in Staging.

**Comment by sebjf** [comment]
Hi @carmenfan, 

I did some regression tests and found a bug (though older than the optimisations...) which has now been fixed, so the bouncer is ready to go back to 3065.

Before I ask Keif to update it though, do you want me to revert the [optimisation](https://github.com/3drepo/3drepobouncer/commit/116a4cae812888bcd21b1c1464006fddb903861c) that keeps the vectors used by getTransMatrix at the file/object scope?
This is worth about 8 percentage points performance improvement, but means the function is not thread safe. I am not sure which you'd consider more important...

**Comment by carmenfan** [comment]
@sebjf could we make it thread safe instead? 😆 

Is that 8% the work you did to make it as quick as before or is this additional savings?

My preference would be not to introduce code that is not thread safe.

**Comment by sebjf** [comment]
Hi @carmenfan, it is additional savings! I'll revert it.
