### ISSUE TITLE
Try out IFC++

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#579]
### Description
Try out IFC++ and see if we can integrate that and replace IFCOpenShell and get significant benefits

### Goals
- Use IFC++ to process IFC files
- The end result geometry should be accurate
- We should be able to generate the same tree
- We should be able to gather the same metadata

### Tasks
- [ ] Compile IFC++
- [ ] Integrate IFC++ into 3drepobouncer
- [ ] Write model importer with IFC++
- [ ] Examine difference in import times
- [ ] Ensure data is correct

### Related Resources
https://github.com/ifcquery/ifcplusplus

**Comment by carmenfan** [comment]
Documented findings: 
![image](https://user-images.githubusercontent.com/11945337/174617438-3961c642-2384-49e9-9ef1-347b629c6fa7.png)

**Comment by AsiteZane** [comment]
@carmenfan what would you like to do with this?

**Comment by carmenfan** [comment]
> @carmenfan what would you like to do with this?

depends... The value in this is that they generate geometry significantly faster than IfcOpenShell, meaning we could import IFCs a lot faster than currently.

By the looks of the tickets on ifc++ they didn't address the problem I discovered. though this is something our own graphics team could work on and resolve if necessary (but we would be essentially fixing a significant problem on a open source library where we have to give away the IP). But it is also possible that they are generating geometry faster because they're not generating it properly.... so we may find that once we've resolved the problem we're not gaining much afterall.. On top of that IFCOpenShell is a much better maintained, mature library in comparison so I do have my reservations about using this one instead. But there's also other advantages, e.g. IfcOpenshell is on LGPL license whereas this one is MIT, so if we decide to close-source 3drepobouncer there is no cost involved.

The other approach is to look at IFCOpenshell. There are settings we can tweak to see whether we can improve the situation. On top of that I believe if if we do #644 for IFC import as well we will most likely find ourselves with a good amount of speed gain (at the moment we're generating crazily detailed geometry - which takes time and also memory/storage).

**Comment by AsiteZane** [comment]
Thank you, something then to revisit later as a research project when we have little to do and wonder whether there's any merit in this :)

I'll keep it for priority scoping but very low.
