### ISSUE TITLE
Mesh optimisation

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#599]
### Description

We have seen a number of models from customers which have a high number of polygons, often on elements which do not warrant such a high number eg. pipe insulation or steel beams.

We will look to have an optional flag at upload which allows the bouncer to reduce the number of polygons on objects that do not warrant them, thus improving performance in the viewer

### Goals

- [x] Identify mesh optimisation algorithm
- [x] Identify meshes within a model that would benefit from mesh optimisation
- [ ] Implement mesh optimisation with direct configuration

### Tasks

- [x] Make units are accessible from import (e.g. in meshnodes themselves)
- [x] Create measure of mesh efficiency (triangles, or vertices, per m3)
- [x] Pick a library
- [x] Expose the target efficiency as a parameter
- [x] Create new optimiser and add to `ImportFromFile`
- [x] Iterate over meshnodes checking for compatibility and suitability
- [x] Convert MeshNode to mutable type
- [x] Convert mutable type back to MeshNode
- [x] Refactor bouncer to never try to store binary data in the BSON
- [x] Replace node in `default` scene with updated content but leaving everything else intact
- [x] Add the simplification algorithm
- [x] Add support for applying units to the parameter
- [ ] Do proper cmake integration
- [x] Add a PMP class to perform vertex collapse
- [x] Test long running file
- [ ] Add performance metrics to log file
- [ ] Fix unit tests (regression)
- [ ] Figure out why Manifold algorithm breaks Decimation
- [ ] Update code so if we have degenerate triangles, ignore just that triangle

PMP specifics

- [x] Remove Eigen or confirm MPL
- [x] Upgrade bouncer to C++17 or shim std::filesystem

### Related Resources
Models:
- Issue with pipe insulation: https://www.dropbox.com/s/lfnz3nkgvj2kt92
- Issue with metsec steel https://www.dropbox.com/s/6lr448u2b97zjq4
- Issue with fence https://www.dropbox.com/s/qf2ukji3bhuf2n2
- Issue with sheet pile https://www.dropbox.com/s/vh8svy5c16v8gb0/

**Comment by mosment3DRepo** [comment]
**Update from sprint:**

We should measure efficiency of mesh in vertices by bounding box volume. This will be selected by the user on upload, either via a Low, Medium, High selection or a direct value.

This requires us to understand the size of the bounding box so we need to extract the units of measure from the file

**Comment by sebjf** [comment]
Some notes...

**Units**

At present, the units extracted from the files will only be used to control the decimation, which only happens on import.

For the units system (i.e. working out factors), Boost has a units system, though it is compile time only. Therefore the units should be stored for now as a factor (e.g. for converting to meters).

Currently there is no concept of a model in the database. In the future it could be valuable to store units, for when we work on coordinate systems, and possibly support mixing meshes of different units. However as the necessary functionality is still to be defined, the scale factor could go on `RepoScene`. This is the one type that doesn't have a direct counterpart in the database. `RepoScene` populates, and reads, from a number of different documents. Not all its members are stored.


**Setting Units**

There are eight locations `RepoScene` instances are created (where we may want to set units):

```
IFCUtilsParser::generateRepoScene()
RepoModelImport::generateRepoScene()
AssimpModelImport::convertAiSceneToRepoScene()
OdaModelImport::generateRepoScene()
```
```
SceneManager::fetchScene()
RepoManipulator::createFederatedScene()
RepoManipulator::saveOriginalFiles()
RepoScene::populate()
```

Of these, the top four methods actually involve creating meshes.

**IFC**

`ifcHelper::IFCUtilsGeometry::generateGeometry()`

`MeshNodes` are instantiated from a set of vertex arrays extracted from the file.



**BIM**

`RepoModelImport::generateRepoScene()`

`MeshNodes` are instantiated from the `meshEntries` array, which is itself populated from a property tree.



**Assimp**

`AssimpModelImport::convertAiSceneToRepoScene()`

`MeshNodes` are created from `aiMesh` instances, and then baked later on in `createTransformationNodesRecursive`.


**ODA**

`OdaModelImport::generateRepoScene()`

`MeshNodes` are instantiated in a number of places and added to the dictionaries in the `odaHelper::GeometryCollecto`r type. They are then retrieved to populate the `RepoScene`.


**Performing Mesh Decimation**

The mesh decimation should occur on the Default graph. This is because it will reduce the amount of geometry stored in the database. There is no mechanism (exposed to the user) to re-stash a model with updated parameters.

The model importer abstraction `ModelImportAbstract` creates a `RepoScene` from the above importers. Immediately after the scene is created, `generateStashGraph()` is called, which invokes the multipart optimiser to build the stash graph.

The `Default` graph is written by `RepoScene::commit()`. This is called after the stash graph is created & committed by `importFileAndCommit`.

The best place to perform the optimisation is in `ModelImportManager::ImportFromFile`. This method already applies optional optimisations and modifications (reducing transforms, and rotating models) and occurs before the stash is constructed.

**Comment by sebjf** [comment]
**Detail Metric**

The first version of the parameterisation will be controlled by a user provided metric, Detail, which is defined as the Number of Vertices per m^3.

To find some potentially suitable guidelines for this value, we can compare the distribution of this metric for four problematic models, with a representative model (rac_sample_house).

![image](https://user-images.githubusercontent.com/5058369/229499978-0a1376c5-f136-40ab-a6e9-a911e18b9adc.png)

The distributions generally have very long tails, including for the sample house.

The axes lines show the standard deviations of each plot.

Some notes on the individual files:

`30084` is the model of the Piles. Each pile is modelled with relatively though not excessively high detail, but when instanced in the number provided, the model as a whole becomes too heavy. It is actually surprising given how homogenous this model is that its detail is distributed at all!

![image](https://user-images.githubusercontent.com/5058369/229500981-e4ddbf1b-74c2-4cc7-a93e-535f774df391.png)

`300090` is a model of a set of fences.

![image](https://user-images.githubusercontent.com/5058369/229501439-fdf3231b-155a-4faf-9162-8f7656382e2a.png)


`BIM_ProjectCoordination_MEP2` is a mechanical model which contains a number of highly detailed parts.

![image](https://user-images.githubusercontent.com/5058369/229500622-5efa2f5e-a446-417b-9a0b-4865e1c214c1.png)

`P01` is the full structural model of a building

![image](https://user-images.githubusercontent.com/5058369/229501918-9efade96-5ed5-4b9c-8bd7-dc2ec2a10f6d.png)

In all cases the outliers are 'real' in the sense that there are highly detailed elements - the high Detail metrics are not due to, for example, 2D items dividing by zero.

Based on the above we could consider looking at the range around 2000 vertices/m^3.

As the decimation algorithm takes a target number of vertices, we can model the effect on model size of arbitrary Detail settings for each model above.

![image](https://user-images.githubusercontent.com/5058369/229521050-fd723ca0-3eae-4b35-bf29-d5c6506611ac.png)

The x-axis the Detail, in N/m^3, and the y-axis is the ratio by which the model would be reduced. Axes lines indicate the 1x and 10x reduction levels.

From this plot we can see that there is a well defined knee for most models. We also see that a 10x model reduction is achieved for the responsive models at just under 1000.

How well behaved the metric is as a control variable is mixed; on one hand the rac model is unresponsive, as indicated by the very flat plot, which is good as this model is representative of a 'good' one, but neither is the problematic P01 model responsive.

**Comment by sebjf** [comment]
**Review (in progress)**

The head of 599 has been updated with a new optimiser, based on [PMP](https://www.pmp-library.org/index.html). This required a number of pre-processing stages be [added](https://github.com/3drepo/pmp-library) to the library that were unexpected, due to the topology not being connected as much as possible and so causing suboptimal performance of the decimation.

At this stage we can review the performance of the decimation with regards to a number of models.

The head has two configuration parameters, Quality and Vertex. Vertex is required to prevent simplification of very simple models (imagine a single cube spread over 100m2). Below is an example of a test configuration. (The only way to specify simplification parameters is via the Json config - there are no CLI arguments for them.)

```
{
	"database": "sebjf",
	"project": "736ec950-ee53-11ed-80ba-ff5ad6a3b522",
	"units": "m",
	"quality": 1000,
	"vertexCount":100,
	"tag": "1000",
	"file": "D:/3drepo/ISSUE_599/rac_basic_sample_project_mm.rvt"
}
```

For the following tests Quality has been set as 1000 and Vertex to 100. The builds were RelWithDebug with optimisations on, but the imports were run under the debugger.

In addition to bouncer, the fork of PMP has been updated with a new sample to explore the behaviour of the pre-processed decimation, for us to compare the theoretical quality of the PMP implementation, with what we see in the viewer.

The current bouncer takes 532 ms to simplify the rac_basic_sample_house from 277011 to 196179 vertices (1.41x). The test settings (1000,100) should ideally not affect the model, though in practice a couple of meshes are above this threshold.

For the most part the model is unchanged, as expected, but in the fine detail meshes there are a number of failures.

![image](https://github.com/3drepo/3drepobouncer/assets/5058369/6aec5ab4-b511-431e-80dd-7ab962937d05)

It takes 782772 ms (13 minutes) to simplify 5213850-ATK-01-XX-M3DM-C-300084 from 71693630 to 4603591 vertices (15.5x). (The typical reduction is from 37150 to 2173, per pile). 

![image](https://github.com/3drepo/3drepobouncer/assets/5058369/f2197af4-c77e-40a7-b951-0814bcf7606f)

In this model, the quality is as good as expected in the feasibility investigation.

The downside is that it is actually possible to reduce further, to say 800-900 vertices per file (another 2x reduction). But the simplistic control parameters do not allow basing this on the mesh.

![image](https://github.com/3drepo/3drepobouncer/assets/5058369/daf2ca24-0413-44a6-9a57-20844de175c7)


It takes 266167 ms (~5 minutes) to reduce BIM_ProjectCoordination_MEP2 from 59606407 to 13873380 vertices (4.3x). For this model, the NWC (not IFC) was used for the import.

![image](https://github.com/3drepo/3drepobouncer/assets/5058369/b7360347-6ca9-41a0-9650-72af6ce1b8f9)

The typical mesh in this model is 100-1000 vertices and is reduced to 100 vertices. This model fails at least one element with an exception "Exception SurfaceMesh::add_face: Complex edge. simplifying mesh 5755b597-b4a2-48ee-a06e-0b7d2a5fa725". This exception occurs when the PMP representation is being built (i.e. before the decimation). The complex edge message means there are three coincident edges.

From those that are decimated, some parts of the model look clean but the decimation fails saliently in others. This model is particularly challenging because individual elements are already quite small - it is sheer number of them (~80,000) that create the problem.


**Sample**

The merge sample in the pmp fork has been updated with the exact bouncer code used to perform the decimation. Additionally the pmp fork has been adapted to allow compilation on gcc 9.8 (c++14) including export. This means the exact representation of the mesh from bouncer can be intercepted and exported for experimentation in the sample, and have the exact same algorithms run on it. This is how we can determine lower thresholds for the theoretical quality of individual elements.

**Comment by carmenfan** [comment]
closing due to abandonment 😢
