### ISSUE TITLE
Take in a units value from configuration file and apply it to the model import where possible

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#611]
### Description
There can be a discrepancy between the file's unit models and the model settings units due to user errors (or in the case of IFC, it can be non deterministic depending on the way it is exported)

For BIM file formats we can pull out the units from the file, so we should take into account of what is our model setting units and apply a scaling so it matches

Where it is impossible (e.g. obj), there should be no scaling applied.

### Goals
- [x] Read in a units from the model import config file and apply scaling
- [x] Do not apply scaling if the file does not have units information

### Tasks
- [x] Add code to support reading units in from the configuration file
  - [x] Thread this information through to the model importer
- [x] Add new virtual function for getting units from the abstract importer
  - [x] Implement the response for all applicable importer types
    - [x] .bim - unknown (We don't record units)
    - [x] .spm - can be found in worldSettings
    - [x] .ifc - will always be in metres as per #600 
    - [x] assimp - Unknown (Most file formats we support through this is unit less anyway [fbx is also unitless](https://forums.autodesk.com/t5/fbx-forum/fbx-units-and-scaling/m-p/9811613/highlight/true#M10079))
    - [x] ODA 
      - [x] rvt
      - [x] dgn/dwg
      - [x] navis
- [x] Add scaling logic onto the importer
- [x] Create a pairing issue for 3drepo.io to make necessary changes
