### ISSUE TITLE
Reduce the amount of files we write

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#626]
### Description

At the moment we're writing a lot of tiny files when we do model processing, every binary array that we used to put into gridfs is a file.

We know that reading many small tiny files is not as efficient as reading one big file, and at the moment majority of our I/O is spent on writing to FS, for e.g:
![image](https://github.com/3drepo/3drepobouncer/assets/11945337/e96c80fa-7818-48ed-bebf-8e2b780c5495)

We can optimise this by writing one blob file to storage instead, or separate it by types of data - eg all vertices goes into a file, all faces goes into a file etc. And we read the desired data using `fseek` when required.

This will also require changes on .io as we also read scene binaries for the purposes such as measuring tools.

##### history.ref
- 1 file added (original model file)

##### scene.ref
- 2-4 files per mesh (one file each for: vertices, faces, normals, UVs)
- 1 file per texture (texture image)

##### stash.3drepo.ref
- 2-4 files per super mesh (one file each for: vertices, faces, normals, UVs)
- 1 file per texture (texture image)

##### stash.json_mpc.ref
1 of each: 
  - fulltree.json
  - idMap.json
  - idToMeshes.json
  - tree_path.json
  - supermeshes.json 
- 1 file per supermesh (unity metadata mapping)

##### stash.unity3d.ref
- 1 file per supermesh

##### sequences.ref
- 1 file per state within the sequence
- 
##### activities.ref
- 1 file per sequence (cached activity tree)

### Proposed changes
The main issue is on the scene graph, having meshes generating at least 2 files each is problematic.

Nodes on the scene graph is [committed on a one by one ](https://github.com/3drepo/3drepobouncer/blob/628ac5d33c745572277334101ccf0f4297b42876/bouncer/src/repo/core/model/collection/repo_scene.cpp#L849)basis.

The least discruptive solution would be to just change this function. 2 things we could do here:

1. we should commit nodes in batches instead of one by one to reduce the amount of handshaking we are doing with mongo (address #627)
2. whilst we collecting the node batches to commit, extract the big files from each node that has them, and add them to blob files, updating the node with a reference to the blob before commiting.

As we are changing the reference we are storing in mongo, we need to make sure that we change the way applications read the data (when we fetch scenes, and also 3drepo.io where it get scene info for things like measuring tools)

### Goals
- [x] To significantly reduce the amount of files we write on large models
- [x] Ensure data is written correctly and well referenced
- [x] Ensure data is reading the new structure correctly
  - [x] 3drepo.io
  - [x] 3drepobouncer
- [x] Ensure the application still understands how to read the old references
  - [x] 3drepo.io
  - [x] 3drepobouncer

### Tasks
- [x] Create a BlobStorageHandler
  - [x] With function that takes in the data and returns a reference
  - [x] With a function that takes in a reference and returns the data
  - [x] Impose a max file size so it creates a new file when finished
  - [x] A finish function so BlobStorageHandler knows when to stop
  - [x] Add a reference to the revision so it's easier to keep track
- [x] Update commitNodes function:
  - [x] to commit nodes in batches
  - [x] to extract binary data and save through blobStorageHandler
- [x] Update fetchScenes node population to read from blobStorangeHandler
- [x] Ensure 3drepo.io reads are consistent(https://github.com/3drepo/3drepo.io/issues/4260)
- [x] Ensure we still know how to read old schema

- [x] Clean ups
  - [x] Check inserts and upserts whether they need to support bigFiles somehow.
  - [x] Replace hard coded strings with constants

### Test Cases
With 100MB as the file size limit, tested locally (deployments may take longer due to network drives):

| file  | [old] commit time  | [old] nFiles |  [new] commit time  | [new] nFiles | 
|---|---|---|---|---|
| rac_basic_sample_project.ifc  |  5s |  2100    | <1s  | 1 | 
| sampleNavis.nwd  | 12mins |  284635   |    1min9s |  14 |
