### ISSUE TITLE
Synchro 6.5.3.7 support

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#655]
### Description
add support for synchro 6.5.3.7.
Majority of the work is done in https://github.com/3drepo/SynchroReader/issues/13

### Goals
- [x] To be able to import an SPM file from 6.5.3.7

### Tasks
- [x] Update travis to use the latest synchro library
- [ ] Add test files for this version
