### ISSUE TITLE
Add support for AssetGenerator

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#666]
### Description

We want to [replace Unity AssetBundles with our own transport format](https://github.com/3drepo/3drepounity/issues/501) that will bypass the WASM VM, and load faster. These assets will be built by a separate library.

### Goals

- [x] [AssetGenerator](https://github.com/3drepo/AssetGenerator) is an optional dependency 
- [x] Control is based on a CMake argument
- [x] Bundles are built using the [AssetGenerator](https://github.com/3drepo/AssetGenerator) library and written to the database

### Tasks

- [x] Add AssetGenerator as a git submodule
- [x] Update AssetsList so that it can support different assets

### Related Resources

Product Issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/376

**Comment by sebjf** [comment]
Things to discuss:

1. How to determine assets lists? 

* Currently unityAssets reads the document in .stash.unity3d for the revision, which contains all the assets as well as the offset.
* For SRCs, the response is built dynamically by iterating each mesh in .stash.3drepo and adding the offset from the revision (we have discussed removing the stash however...)
