### ISSUE TITLE
bouncer should free the graph after the stash graph has been created

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#683]
### Description

After creating the stash graph, bouncer should free any unused resources to limit peak memory.

This is in response to a file that is exceeding the 26 Gb limit of the Pods due to the number of instances.

This should be a straightforward case of implementing a default graph equivalent of `clearStash` and calling it in `commitScene`, since the graphs should never be used at the same time. Though, we probably want to refactor all references to graph in RepoScene, to be sure that nothing attempts to load an unloaded default graph.

### Goals

- [ ] Default graph is freed before RepoBundles are created.

### Tasks

- [ ] Implement `clearDefault()` on `RepoScene`
- [ ] Call after the selection tree is generated
- [ ] Add checks to detect if the default tree has been unloaded

### Related Resources

MockUp : `link to mockup`
Coda doc: `link to coda`

**Comment by sebjf** [comment]
Addressed by https://github.com/3drepo/3drepobouncer/issues/682
