### ISSUE TITLE
Decomission gltf support

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#686]
### Description

The gltf exporter is out of date and not used for anything. We should decommission it to reduce the surface we have to support.

### Goals

- [ ] `GLTFModelExport` no longer exists

### Tasks

- [ ] Delete `GLTFModelExport`
- [ ] Remove references to `GLTFModelExport` from e.g. `genStash` etc
- [ ] Update unit tests accordingly

**Comment by sebjf** [comment]
Closing as superseded by https://github.com/3drepo/3drepobouncer/issues/697
