### ISSUE TITLE
Mongo Driver Upgrade - decommissioning

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#697]
### Description

Upgrade the mongo driver; [product ticket](https://github.com/3drepo/3D-Repo-Product-Team/issues/561) with further details.

This issue is for the decommissioning part of that ticket, the purpose of which is to clean up the bouncer codebase so we only focus on refactoring the bits we still use.

### Goals

- [ ] Remove legacy functions of bouncer that are no longer part of its use case

### Tasks

- [x] Ensure 462 is merged
- [x] Remove diff functionality
- [x] Remove role and user functionality
- [x] Remove cameras
- [x] Remove project settings
- [x] Remove gridfs
- [x] Remove matrix logic from generateFederation 
- [x] Remove getFile from client
- [x] Remove GLTF exporter
- [x] Remove any remaining (publicly) unused db operations (countItemsInCollection, removeCollection, removeDocument, hasDatabase, getNameOfAdminDatabase, getDatabasesWithProjects, getDatabases, fetchDatabases)

**Comment by sebjf** [comment]
Random remarks on mongo driver...

**ABI**

The developers practice support for ABI versioning.

The intent is not for developers to target one of these directly but to use the root namespace, which will redeclare methods between ABI versions as needed. That is, if the ABI changes this would require a recompile, but the API is unchanged and so the upgrade is seamless for existing APIs with regards to source. New APIs are added in the new ABI that is being compiled for.

Targeting the ABIs directly is available for developers who have stability policies of their own. AFAIK this is not us, as we have no stability policy, and we deliver binaries to Travis directly that are immutable between upgrades of the driver version in bouncer.

**Build Config**

The API will apparently change depending on build configuration. This should not be a big deal for us because we only really have one build configuration.

**Delivery**

The documentation makes references to package managers, but it doesn't seem the driver is in any ubuntu packages so far, so we will need to continue to build and deliver copies ourselves.

The driver offers [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) configs. Again, the utility of this for us seems limited given that its another tool to install on Travis, and we only need to support one version at a time.

**Comment by sebjf** [comment]
Remarks on the current operation of bouncer...


### Database Mangers and Handlers

AbstractDatabaseHandler provides an abstraction of the database driver, which works with RepoBSON objects (but no more specialised). This is an abstract class that is implemented by MongoDatabaseHandler. One of the important tasks of MongoDatabaseHandler's abstraction, is to handle the binary mappings associated with RepoNodes, writing them to a file with BlobFilesHandler when the node is committed to the database.

The RepoController API shares some responsibility with AbstractDatabaseHandler, in the sense that it defines a database API, but at a higher level, operating with concrete RepoBSON types such as RepoScene. In almost all cases the RepoController APIs call the corresponding API from RepoManipulator.

RepoToken holds database credentials. These are not currently used however - the database address is ignored by the getHandler method of the DatabaseHandler and the token does not hold an object describing the actual state.

FileManager is predominantly concerned with updating data on disk, however it maintains a reference to AbstractDatabaseHandler which it uses to create and update ref nodes. This is set when the FileManager singleton is initialised, and FileManager and the database handler are considered separate hence.


### Workers and Connection Pools

The design of the RepoController API suggests support for multiple workers. In practice RepoController always creates one worker (RepoManipulator), which in turn initialises a MongoDatabaseHandler and a FileManager. The latter two classes maintain a singleton. Beneath the MongoDatabaseHandler is the Mongo client - a static class offering access to the Mongo driver.


### Pimpl Idiom and RepoManipulator

RepoController uses the pimpl pattern to hide its dependencies from other users. We don't really have other uses of bouncer, and _RepoControllerImpl doesn't have many private members. It is not worth refactoring anything around this, but also its good in that there isn't much to break.

In a way, the actual private implementation of RepoController is RepoManipulator, as almost all RepoControllerImpl methods call a paired method from this. (As above, while RepoController will pop a worker from the pool, in practice there is only one worker).


### Connection and Authentication

The first time the Mongo driver actually makes a connection is through the creation of the MongoDatabaseHandler singleton.


### Example

As an exercise, we follow the control flow of the commands of the client, to see how the nodes are constructed and how the database API is used.


1. 3drepobouncerClient instantiates a RepoController. This creates a number of RepoManipulator instances and pushes them to the worker pool. RepoController is only ever instantiated with one worker and one db connection.

2. The RepoConfig is read from a JSON file and used to initialise the RepoController. This initialises the worker and creates a RepoToken holding the db address. `connectAndAuthenticateWithAdmin` calls the static AbstractDatabaseHandler getHandler method, the intent of which is to make an underlying connection that can later be retrieved with another call to getHandler, providing the host. As it is, this initialise the Mongo client (globally), and sets a singleton in MongoDatabaseHandler, which is always returned by `getHandler(host)`.

3. Before the initialisation is complete, RepoManipulator will also instantiate the FileManager singleton.

4. The operation is performed. This is passed the RepoToken created above.

5. importFileAndCommit

a. RepoController (RepoManipulator) creates a RepoScene from a filepath. 

b. The RepoScene is created by a ModelImportManager instance. How this is done varies. For ODA for example, the file is read into a GeometryCollector instance and a RepoScene constructed from this. The RepoScene instance is created via its constructor and configured in one place (e.g. via setWorldOffset and similar methods) (note how this differs to types that subclass RepoNode).

c. Types that subclass RepoNode are constructed by factory methods. The RepoScene consists of TransformationNodes, MeshNodes, MaterialNodes, TextureNodes, MetadataNodes, RepoTasks and a RepoSequence. RepoScene can also hold cameras, references and unknowns. Cameras we can drop. unknowns exist to hold nodes that are read from a scene document from the database. In this case, the node types are only identified at runtime (via a field). The unknowns just hold all nodes that cannot be identified. 

d. Once the RepoScene has been populated, ModelImportManager will perform post-processing. For example, a scale TransformationNode will be applied to the root to correct the units. The process of updating the transformation is involved; the existing node is first cloned and the scale applied to the transform matrix, then the root node in the transform graph is modified. This involves replacing the node using the RepoScene::modifyNode operation, which is discussed further below.

e. The stash graph is generated using a new instance of SceneManager. This updates the stash repoGraphInstance using an instance of MultipartOptimizer. MultipartOptimizer operates on baked instances of MeshNodes. These instances are no longer written to the database in the current version of bouncer. SupermeshNode similarly is an entire type that is never written, but subclasses from MeshNode since it is a specialisation of a mesh. The stash graph contains only transforms and meshes and used to build the web buffers. Metadata associations are maintained through mappings to the original ids in the default graph.

d. RepoController (RepoManipulator) commitScene is where the RepoScene nodes are written to the database. The AbstractDatabaseHandler and FileManager singletons are acquired by the RepoManipulator.

e. The actual writing of the scene contents is performed by RepoScene itself as its schema is quite complex. RepoScene will try to insert a ProjectSettings, create a RevisionNode, create an issues collection (if necessary), and write them one by one. During this stage, any binary vectors are moved into the binary mappings of the node and outside the BSON.

f. Finally, the sequences are committed. 

g. The SceneManager will then build and write the web buffers. Each exporter has its own implementation, but will return a repo_web_buffers_t. The type hierarchy of this object is independent of the database types. RepoSceneManager will write the buffers using the FileManager and update the assets document in the database.

h. The RevisionNode is updated with a new status by upserting the revised RevisionNode in the history collection.



6. genStash

a. The web buffers and selection tree are rebuild from a Default scene.

b. The RepoScene is fetched from the database. This operation is performed by SceneManager. The process of loading is to get all nodes in the .scene collection with a particular revision specified, then to distribute them into a repoGraphInstance instance based on the type (the `populate` method).

c. Operations are then run to produce repo_web_bufferts_t or a selection tree (with SelectionTreeMaker); both pathways construct a set of byte arrays that are written to the database as ref nodes, and take place via SceneManager.


7. createFed

a. Produces a RepoScene that is a federation - i.e. it consists only of TransformNodes and ReferenceNodes. 

b. The ReferenceNodes are created via the corresponding factory method. The ReferenceNode holds the reference to the container. generateFederation will build a matrix but it is not used anywhere.

c. RepoManipulator (not SceneManager) will then create an instance of RepoScene. The method generates TransformationNodes for the root and each group, under which the ReferenceNodes are parented. The RepoScene is built from these sets using its constructor.

b. That scene is then committed via the RepoController passed to generateFederation.


8. getFile

a. Retrieves files (that were used to create a RepoScene) from the database and writes them to a directory

b. RepoManipulator will load a revision into a new RepoScene. The Revision (which exists as a ModelRevisionNode) is retrieved from the history collection (by RepoScene) and holds the rFile reference which points to the original file. This operation does *not* populate all the nodes, just the `revNode`.

c. RepoManipulator then operates on the RepoScene to ask it to get the rFile entries, then RepoManipulator directly reads the contents of each entry using the FileManager [4].



### Schema Patterns

There are three patterns involved in bouncer that relate to how the database schema is defined and implemented:

1. RepoNode subclasses are committed to the database 'directly' as objects and manage their schema through maintaining document fields on themselves.

2. RepoScene represents a schema similar to a RepoNode subclass, in the sense that a scene is a 'thing' that exists. However this schema is more complex, and spread across multiple collections and documents. RepoScene uses the AbstractDatabaseHandler API to update documents to maintain the scene in the database. This concept leaks in places: RepoScene for example will change the project settings. It will also update RevisionNode instances, which are updated elsewhere too (e.g. by RepoManipulator).

3. SceneManager is one level above a RepoScene, and will act as a controller over a RepoScene. It is responsible for the assets schema and some ref nodes, but in a way that it's clear that SceneManager and the objects it manages are distinct. The same pattern is seen in DrawingManager.

4. RepoManipulator performs higher level database operations, such as enumerating collections.



### Swaps and Modifies

As RepoBSON types are immutable, where bouncer needs to modify an identity or node mid-way through the tree, the process followed is to clone the document, updating some fields as it goes, and to replace the node. There is another aspect to modifying the graph too, in that scenes are revisioned. When working on the default graph, the sharedId of a node follows that node between revisions, but the nodes for a given revision Id are cloned with new unique Ids.

The Mongo BSON swap operation is used to replace the reference to a document for a given BSON instance.

The RepoScene::modifyNode method performs an update of a node, creating a new one for the new revision. modifyNode will keep track of nodes that have been newly created and modified for later commits.

There is some discussion about this functionality however:

1. Bouncer will populate a RepoScene by enumerating all nodes holding a specific revision Id, and inherence is supported via *parent* members, not *child* members. That means that if a RepoScene is loaded, modified, and written, then loading that revision again won't actually load all the associated nodes, as only the 'modified' nodes would be read from the database.

2. There doesn't seem to be a current control flow in which a scene is actually modified by bouncer; bouncer either imports files into new revisions, or it creates a new scene as a federation. In both cases all the nodes built (MeshNodes, TransformationNodes, ReferenceNodes, etc) are new. So, the set of nodes in the .scene collection associated with any two RevisionNodes, are always disjoint.




### Discussion

1. FileManager and AbstractDatabaseHandler are passed around as if they are independent, but they are not because FileManager maintains a reference to AbstractDatabaseHandler. Do we want to make this coupling explicit (e.g. through a 'combined' handler?)

2. RepoNode inheriting from Mongo documents is not best practice. We could make this work with the new driver API, but it leaves us with the same problem for the future (breaking API changes having a big impact). Further, the immutable nature of these instances makes the code to handle objects more complex than it needs to be, than if these types were more traditional representations of transforms, meshes etc. One part of the refactor should be to break this inheritance.



### Deprecated types and code

There is some code that is no longer used, which we can remove.

1. RepoManipulator::compareScenes, along with AbstractDiff and its subclasses
2. RepoManipulator project, role and user management, and their associated types (RepoUser and RepoRole)
3. repo_stack.cpp (is an empty file)
4. CameraNode and the camera optimisation stages of TransformationReductionOptimizer

Additionally, it seems we can do the following, but this should have some further discussion:

1. RepoScene creates an entry in the settings collection for the project settings. This only (from bouncer) says whether the entry is a federation. Is the Project Settings document created by the frontend now, and if so shall we remove RepoProjectSettings from bouncer?
2. We do not use GridFS any more, so we could remove the GridFS file handler?
3. The matrix built in `generateFederation` does not appear to be used - shall we remove this snippet?
4. The getFile method of 3drepobouncerClient does not decompress gzipped references - does this imply that this is not being used anywhere currently and so can be decommissioned?
