### ISSUE TITLE
Mongo Driver Upgrade - Mongo type decoupling

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepobouncer#703]
### Description

Upgrade the mongo driver; [product ticket](https://github.com/3drepo/3D-Repo-Product-Team/issues/561) with further details.

This issue is for the decoupling of the mongo dependencies, which is also described by this ticket: https://github.com/3drepo/3D-Repo-Product-Team/issues/560

This branch relies on https://github.com/3drepo/3drepobouncer/issues/697

### Goals

- [ ] RepoBSON no longer inherits from BSONObj publicly
- [ ] RepoBSON and RepoBSONBuilder are isolated to the minimum number of modules possible (Nodes and Bsons)
- [ ] There are no mongo references outside of MongoDatabaseHandler

### Tasks

- [x] Refactor DrawingRevisionNode
- [x] Refactor MaterialNode
- [x] Refactor MeshNode
- [x] Refactor MetadataNode
- [x] Refactor ModelRevisionNode
- [x] Refactor ReferenceNode
- [x] Refactor RevisionNode
- [x] Refactor SupermeshNode
- [x] Refactor TextureNode
- [x] Refactor TransformationNode
- [x] Update RepoNode tests
- [x] Update DrawingRevisionNode tests
- [x] Update MaterialNode tests
- [x] Update MeshNode tests
- [x] Update MetadataNode tests
- [x] Update ModelRevisionNode tests
- [x] Update model revision handling to make file prefix not implicit
- [x] Update ReferenceNode tests
- [x] Update TextureNode tests
- [x] Update TransformationNode tests
- [x] Update RepoTask
- [x] Create RepoTask unit tests
- [x] Create RepoSequence unit tests
- [x] Update RepoCalibration
- [x] Make RepoProjectSettings unit tests
- [x] Update RepoProjectSettings
- [x] Go through header files to clean up, make classes forward declared where possible
- [x] Remove filename support from bin mappings
- [x] Refactor binary file handling so they come from inside the bin mappings only and remove the shrink option during writing the RepoScene
- [x] Update RepoBSON unit tests
- [x] Add BSON Element unit tests
- [x] Update RepoBSONBuilder unit tests
- [x] Update MongoDatabaseHandler unit tests
- [x] Refactor all the cloneAndAddParent calls
- [x] Run linter
- [x] Extend Trans Optimiser Tests
- [x] Run full suite of unit tests
- [x] Refactor the metadata stuff in files handler to use variants
- [x] Update factory methods to use the methods/constructors of the mutable types
- [x] Get it to build on linux
- [ ] Fix all tests on Travis

No longer doing as part of this: 

- [ ] Replace usage of repo_material_t with MaterialNode
- [ ] Make a criteria type to hand to database handler so other types can stop relying on the builder
- [ ] Refactor to forward declare all mongo types in mongo database handler header

### Manual Tests

- [x] Drawing DWG/Autocalibration
- [x] Drawing PDF/Manual Calibration
- [x] ODA Import (Revit House, MCFC)
- [x] Revit Systems Import
- [x] NWD Federation Import
- [x] Revisions & Diff (Clinic A)
- [x] IFC Import (Impraria)
- [x] SPM Import (Clinic S Landscape, Displacement Test)
- [x] Hidden Geometry (Clinic S w/ Landscape)
- [x] FBX Import (Mixed Resolution, Mixed Textured)
- [x] OBJ Import (Multiresolution, Cubes)
- [x] Lines only OBJ Import (Gamma)
- [x] DWG as Model Import (Revit House, Coloured Boxes 3D, Car Park)
- [x] DGN as Model Import
- [x] Sequences and Sequences Color Overrides (Clinic S Landscape, Displacement Test)
- [x] Create, Modify Federation (Car Park)
- [x] Modify Legacy Federation (Empty Containers, Groups)
- [x] genStash on Legacy Import
